name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.19', '1.20' ]
        arch: [ 'amd64', '386' ]
    name: Go ${{ matrix.go }} GOARCH=${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Set GOARCH
        run: |
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV
      - name: Run tests with race detector
        if: env.GOARCH != '386'
        run: go test -v -race -short ./...
      - name: Run all tests
        run: go test -v ./...
      - name: Run RPC tests repeatedly
        run: |
          cd rpc
          go test -c
          for i in `seq 500`; do ./rpc.test; done
